### ISSUE TITLE
Front page doesn't look great

### ISSUE THREAD

**Issue by davorg** [davorg/perlsphere#15]
Currently, the front page of the site contains:

* A post about saws
* Several old posts from Dave Cantrell's blog
* Several old posts about (I think) Haskell

This isn't a particularly good look for a site that says it's the Perl firehose.

I understand that side projects take up more time than you hope they will and that old site projects often get dropped. But I'm wondering if you have any plans to rejuvenate this site. If not, can I suggest that you consider redirecting requests to my Perl Planet site (at https://perl.theplanetarium.org/)? I'll go through your configuration file and grab any still-valid sites that I don't already have on my list.

I also see that the domain registration expires in June 2021. If you don't have time for the project, perhaps you could just let the domain drop.

**Comment by ranguard** [comment]
@davorg The DNS is under the TPF control - via Dan and me. 

I gave @mohawk2 the repo a while ago as I'm not really doing much Perl OS stuff any more and he was getting access via mst.. to the server - not I'm not sure where that got to. 

I don't feel strongly - I used to argue about setting up sites with enough support people around but that ship feels like it's sailed... so if you like setup a cloudflare DNS or something and can make you controller that way.

@mohawk2 I'll co-ordinate point DNS to @davorg in the next couple of weeks unless I hear from you :)

Leo

**Comment by mohawk2** [comment]
@ranguard This has bubbled up to the top of my list - I'm not really clear on how to deploy this in its current form, never mind any future form. I'll be pleased to collaborate with @davorg (or pass this over to him) as people wish. I'll drop you a line to ask about deploy details :-)

**Comment by ranguard** [comment]
@davorg - please setup DNS nameservers somewhere (cloudflare will give you
free DNS nameservers).

Then let me know what they are and I'll get the DNS record up dated to
point there and you can pop in a redirect

Leo

**Comment by davorg** [comment]
Ok. The DNS servers are:

frank.ns.cloudflare.com
lara.ns.cloudflare.com

They're currently configured to point at the existing server. I'll fix that later.

**Comment by ranguard** [comment]
Doh, 2FA on the registra now - I've asked Daniel Wright to do the honours

Will update this ticket when I hear

All the best

Leo

**Comment by mohawk2** [comment]
This repo has now been transferred to @davorg - let me know if I can be any help!

**Comment by davorg** [comment]
I've just had a reminder from Cloudflare that I got halfway through setting this up, but the DNS records still need to be updated.

**Comment by oalders** [comment]
@davorg I should be able to update the DNS for you. Would you like me to do that?

**Comment by davorg** [comment]
@oalders That would be great. My new DNS servers are:

* frank.ns.cloudflare.com
* lara.ns.cloudflare.com

Thanks

**Comment by oalders** [comment]
@davorg I've updated the DNS servers (and I renewed the name for another year as it was coming up in June). Let me know if you need anything else.

**Comment by davorg** [comment]
That's all great. Thanks.

My plan is to redirect the domain to Planet Perl. So this time next year, I doubt there will be a need to renew it again.

**Comment by davorg** [comment]
Right. That's all working now. PerlSphere redirects to Planet Perl. Thanks for your help, everyone.
