### ISSUE TITLE
Reposting of old posts

### ISSUE THREAD

**Issue by matthewpersico** [davorg/perlsphere#7]
Every so often, the feed gets a slew of repostings from Dave's Free Press. As of this issue's creation time, there are about 30 repostings that have crowded out any real new articles.

I would posit that the site is reorging its files somehow giving them all new dates every few weeks.

**Comment by matthewpersico** [comment]
The site appears to be dormant. Only one post every two years and none about Perl. Suggest you remove the site from consideration.

**Comment by matthewpersico** [comment]
Happened again today.

**Comment by mohawk2** [comment]
@DrHyde Any thoughts?

**Comment by DrHyde** [comment]
No idea why posts are re-appearing, nothing's changing at my end.

**Comment by matthewpersico** [comment]
Again today. Can we just exclude http://www.cantrell.org.uk/david/journal/ from the lookup list?

**Comment by matthewpersico** [comment]
Again today. Can we just exclude http://www.cantrell.org.uk/david/journal/ from the lookup list?

**Comment by matthewpersico** [comment]
Again last week. Can we just exclude http://www.cantrell.org.uk/david/journal/ from the lookup list?

**Comment by davorg** [comment]
This site no longer exists, so I guess this issue can be closed :-)
